apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  namespace: user
  labels:
    app: traffic-generator
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
      version: v1
  template:
    metadata:
      labels:
        app: traffic-generator
        version: v1
    spec:
      containers:
      - name: traffic-generator
        image: curlimages/curl:latest
        command: ["/bin/sh"]
        args:
          - -c
          - |
            while true; do
              echo "Generating traffic..."
              curl -s http://auth-service.user/api/auth/health || echo "Auth service not reachable"
              curl -s http://booking-service.user/api/bookings/health || echo "Booking service not reachable"
              curl -s http://flight-service.user/api/flights/health || echo "Flight service not reachable"
              curl -s http://payment-service.user/api/payments/health || echo "Payment service not reachable"
              curl -s http://admin-service.admin/api/admin/health || echo "Admin service not reachable"
              sleep 5
            done
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: traffic-generator
  namespace: user
  labels:
    app: traffic-generator
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: traffic-generator