{{- if .Values.istio.enabled }}
# Admin Namespace mTLS Policy
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: admin
spec:
  mtls:
    mode: STRICT

---
# Admin Namespace DestinationRule
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default
  namespace: admin
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}