# CloudJet Analysis Templates for Auto-Promotion
{{- range $serviceName, $service := .Values.services }}
{{- if and $service.enabled (hasKey $service "rollout") $service.rollout.enabled }}
---
# Health Check Analysis Template
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $service.name }}-health-check-{{ $service.image.tag | replace "." "-" }}
  namespace: {{ $service.namespace | default $.Values.global.namespace }}
spec:
  metrics:
  - name: health-check
    failureLimit: 15         # 매우 관대한 실패 허용 (Pod 시작 시간 고려)
    consecutiveErrorLimit: 15 # 연속 실패 제한도 관대하게
    interval: 30s            # 긴 간격으로 Pod 준비 시간 확보
    count: 20                # 충분한 시도 횟수 (10분간)
    successCondition: result.code == 200
    provider:
      web:
        # 클러스터 내부 DNS가 아닌 Kubernetes API를 통한 헬스체크
        url: "http://{{ $service.name }}-preview.{{ $service.namespace | default $.Values.global.namespace }}.svc.cluster.local:{{ $service.port }}{{- if eq $serviceName "auth" }}/api/auth/health{{- else if eq $serviceName "booking" }}/api/bookings/health{{- else if eq $serviceName "flight" }}/api/flights/health{{- else if eq $serviceName "payment" }}/api/payments/health{{- else if eq $serviceName "admin" }}/api/admin/health{{- end }}"
        timeoutSeconds: 15

  - name: response-time-check
    failureLimit: 15
    consecutiveErrorLimit: 15
    interval: 30s
    count: 12  # failureLimit보다 크게 설정됨
    successCondition: result.code == 200  # HTTP 200 응답만 확인
    provider:
      web:
        url: "http://{{ $service.name }}-preview.{{ $service.namespace | default $.Values.global.namespace }}.svc.cluster.local:{{ $service.port }}{{- if eq $serviceName "auth" }}/api/auth/health{{- else if eq $serviceName "booking" }}/api/bookings/health{{- else if eq $serviceName "flight" }}/api/flights/health{{- else if eq $serviceName "payment" }}/api/payments/health{{- else if eq $serviceName "admin" }}/api/admin/health{{- end }}"
        timeoutSeconds: 15

---
# Performance Analysis Template
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $service.name }}-performance-check-{{ $service.image.tag | replace "." "-" }}
  namespace: {{ $service.namespace | default $.Values.global.namespace }}
spec:
  metrics:
  - name: memory-usage
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          avg(container_memory_working_set_bytes{pod=~"{{ $service.name }}-rollout-.*", container="{{ $service.name }}"}) / 1024 / 1024
    successCondition: result[0] < 400  # 400MB 이하
    failureLimit: 3
    interval: 30s
    count: 4  # 2분간 체크

  - name: cpu-usage
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          avg(rate(container_cpu_usage_seconds_total{pod=~"{{ $service.name }}-rollout-.*", container="{{ $service.name }}"}[1m])) * 100
    successCondition: result[0] < 80  # CPU 80% 이하
    failureLimit: 3
    interval: 30s
    count: 4
{{- end }}
{{- end }}