# CloudJet Analysis Templates for Auto-Promotion
{{- range $serviceName, $service := .Values.services }}
{{- if and $service.enabled (hasKey $service "rollout") $service.rollout.enabled }}
---
# Health Check Analysis Template
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $service.name }}-health-check
  namespace: {{ $service.namespace | default $.Values.global.namespace }}
spec:
  metrics:
  - name: health-check
    provider:
      web:
        # 클러스터 내부 DNS가 아닌 Kubernetes API를 통한 헬스체크
        url: "http://{{ $service.name }}-preview.{{ $service.namespace | default $.Values.global.namespace }}.svc.cluster.local:{{ $service.port }}{{- if eq $serviceName "auth" }}/api/auth/health{{- else if eq $serviceName "booking" }}/api/bookings/health{{- else if eq $serviceName "flight" }}/api/flights/health{{- else if eq $serviceName "payment" }}/api/payments/health{{- else if eq $serviceName "admin" }}/api/admin/health{{- end }}"
        headers:
        - key: Content-Type
          value: application/json
        jsonPath: "{$.status}"
        timeoutSeconds: 5
    successCondition: result == "healthy"
    failureLimit: 3  # count보다 작게 설정
    interval: 15s    # 간격도 늘림
    count: 6         # failureLimit보다 크게 설정

  - name: response-time-check
    provider:
      web:
        url: "http://{{ $service.name }}-preview.{{ $service.namespace | default $.Values.global.namespace }}.svc.cluster.local:{{ $service.port }}{{- if eq $serviceName "auth" }}/api/auth/health{{- else if eq $serviceName "booking" }}/api/bookings/health{{- else if eq $serviceName "flight" }}/api/flights/health{{- else if eq $serviceName "payment" }}/api/payments/health{{- else if eq $serviceName "admin" }}/api/admin/health{{- end }}"
        timeoutSeconds: 5
    successCondition: result < 5000  # 5초 이내 응답 (더 관대하게)
    failureLimit: 2
    interval: 15s
    count: 4  # failureLimit보다 크게 설정됨

---
# Performance Analysis Template
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ $service.name }}-performance-check
  namespace: {{ $service.namespace | default $.Values.global.namespace }}
spec:
  metrics:
  - name: memory-usage
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          avg(container_memory_working_set_bytes{pod=~"{{ $service.name }}-rollout-.*", container="{{ $service.name }}"}) / 1024 / 1024
    successCondition: result[0] < 400  # 400MB 이하
    failureLimit: 3
    interval: 30s
    count: 4  # 2분간 체크

  - name: cpu-usage
    provider:
      prometheus:
        address: http://prometheus.monitoring.svc.cluster.local:9090
        query: |
          avg(rate(container_cpu_usage_seconds_total{pod=~"{{ $service.name }}-rollout-.*", container="{{ $service.name }}"}[1m])) * 100
    successCondition: result[0] < 80  # CPU 80% 이하
    failureLimit: 3
    interval: 30s
    count: 4
{{- end }}
{{- end }}