# CloudJet External Secrets and SecretStores
{{- if .Values.secrets.externalSecrets.enabled }}

# SecretStores for AWS Secrets Manager access
{{- range .Values.global.applicationNamespaces }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $.Values.secrets.externalSecrets.storeName }}
  namespace: {{ . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ $.Values.secrets.externalSecrets.serviceAccountName }}
{{- end }}

# External Secrets for each namespace
{{- range .Values.global.applicationNamespaces }}
---
# Unified External Secret for all application secrets
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudjet-unified-secret
  namespace: {{ . }}
spec:
  refreshInterval: 300s
  secretStoreRef:
    name: {{ $.Values.secrets.externalSecrets.storeName }}
    kind: SecretStore
  target:
    name: cloudjet-secrets
    creationPolicy: Owner
  data:
  # Database secrets
  - secretKey: DB_PASSWORD
    remoteRef:
      key: cloudjet/database
      property: DB_PASSWORD
  # Application secrets
  - secretKey: SECRET_KEY
    remoteRef:
      key: cloudjet/application
      property: SECRET_KEY
  - secretKey: JWT_SECRET
    remoteRef:
      key: cloudjet/application
      property: JWT_SECRET
  # BootPay API secrets
  - secretKey: BOOTPAY_REST_API_KEY
    remoteRef:
      key: cloudjet/bootpay
      property: BOOTPAY_REST_API_KEY
  - secretKey: BOOTPAY_PRIVATE_KEY
    remoteRef:
      key: cloudjet/bootpay
      property: BOOTPAY_PRIVATE_KEY
{{- end }}
{{- end }}