{{- if .Values.istio.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: istio-gateway-external
  namespace: istio-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
  labels:
    app: istio-gateway
    istio: gateway
spec:
  type: LoadBalancer
  selector:
    istio: gateway
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
{{- end }}