# CloudJet ServiceAccounts for External Secrets with IRSA
{{- if .Values.serviceAccounts.enabled }}
{{- range .Values.serviceAccounts.accounts }}
{{- $account := . }}
{{- if .enabled }}
{{- range .namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $account.name }}
  namespace: {{ . }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $account.roleArn }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}