{{- if .Values.istio.enabled }}
# User Namespace mTLS Policy
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Values.global.namespace }}
spec:
  mtls:
    mode: STRICT

---
# User Namespace DestinationRule
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: default
  namespace: {{ .Values.global.namespace }}
spec:
  host: "*.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
{{- end }}