# Minimal Loki v3 with Volume Support
loki:
  auth_enabled: false
  
  limits_config:
    volume_enabled: true
    retention_period: 168h
  
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  
  storage:
    bucketNames:
      chunks: cloudjet-loki-storage-eksd-27b9e47b
      ruler: cloudjet-loki-storage-eksd-27b9e47b
      admin: cloudjet-loki-storage-eksd-27b9e47b
    s3:
      region: ap-northeast-2

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::556683426101:role/loki-irsa-role

write:
  replicas: 2

read:
  replicas: 2

backend:
  replicas: 2

chunksCache:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true