# Loki v3.5.3 Values for CloudJet with S3 Storage and Volume Support
# Modern Loki configuration with all advanced features

# Enable single binary mode for simplicity
deploymentMode: SingleBinary

# Loki configuration
loki:
  # Common configuration
  commonConfig:
    replication_factor: 1
    path_prefix: /var/loki
  
  # Schema configuration for v3
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: cloudjet-loki-index_
          period: 24h

  # Storage configuration
  storage:
    type: s3
    bucketNames:
      chunks: cloudjet-loki-storage-eksd-27b9e47b
      ruler: cloudjet-loki-storage-eksd-27b9e47b
      admin: cloudjet-loki-storage-eksd-27b9e47b
    s3:
      region: ap-northeast-2
      s3ForcePathStyle: false
      insecure: false
  
  # Limits configuration with volume enabled
  limits_config:
    volume_enabled: true
    retention_period: 168h  # 7 days
    max_query_length: 168h
    max_query_parallelism: 32
    max_streams_per_user: 10000
    max_line_size: 256000
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    ingestion_rate_mb: 16
    ingestion_burst_size_mb: 32
    per_stream_rate_limit: 3MB
    per_stream_rate_limit_burst: 15MB

  # Server configuration
  server:
    http_listen_port: 3100
    grpc_listen_port: 9096
    log_level: info

  # Auth
  auth_enabled: false

  # Chunk store config
  chunk_store_config:
    max_look_back_period: 168h

# Single Binary deployment configuration
singleBinary:
  replicas: 1
  
  # Resources
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  
  # Persistence for WAL and temp files
  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp2
    accessModes:
      - ReadWriteOnce

# Service configuration
service:
  type: ClusterIP
  port: 3100

# ServiceAccount configuration
serviceAccount:
  create: true
  name: loki
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::556683426101:role/loki-irsa-role

# Service Monitor for Prometheus
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      app: loki
    interval: 30s
    scrapeTimeout: 10s

# Test configuration
test:
  enabled: false

# Disable chunks cache to reduce memory usage
chunksCache:
  enabled: false

# Disable results cache  
resultsCache:
  enabled: false

# Grafana Agent (instead of Promtail for v3)
promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    
    scrape_configs:
      # CloudJet services in user namespace
      - job_name: cloudjet-user-services
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [user]
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: (auth-service|flight-service|booking-service|payment-service)
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: service

      # CloudJet admin service
      - job_name: cloudjet-admin-service
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [admin]
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: admin-service
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: service