# Jaeger All-in-One Values for CloudJet
# Distributed tracing for microservices in single container

# Global settings
fullnameOverride: "jaeger"
namespaceOverride: "monitoring"

# Distributed Jaeger configuration
agent:
  enabled: true

collector:
  enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  extraEnv:
    - name: COLLECTOR_ZIPKIN_HOST_PORT
      value: ":9411"

query:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  service:
    type: ClusterIP

storage:
  type: memory

# Service configuration
service:
  type: ClusterIP
  ports:
    - name: query-http
      port: 16686
      targetPort: 16686
    - name: collector-grpc
      port: 14250
      targetPort: 14250
    - name: collector-http
      port: 14268
      targetPort: 14268
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318

# Ingress configuration (if needed)
ingress:
  enabled: false

# ServiceMonitor for Prometheus integration
serviceMonitor:
  enabled: true
  labels:
    app: jaeger
  interval: 30s

# Remove UI Configuration section as it's causing issues