global:
  clusterName: "eksdapne2-vazh"

karpenter:
  enabled: true
  
  nodeClasses:
    default:
      name: "default"
      instanceStorePolicy: "RAID0"
      amiFamily: "AL2023"
      role: "eks-eksdapne2-vazh-karpenter-node-instance-role"
      instanceProfile: "eks-eksdapne2-vazh-karpenter-node-instance-profile"
      metadataOptions:
        httpEndpoint: "enabled"
        httpProtocolIPv6: "disabled"
        httpPutResponseHopLimit: 1
        httpTokens: "required"

  nodePools:
    default:
      name: "default"
      nodeClassRef: "default"
      requirements:
        - key: "kubernetes.io/arch"
          operator: "In"
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: "In"
          values: ["spot"]
        - key: "node.kubernetes.io/instance-type"
          operator: "In"
          values: ["t3.large"]
        - key: "topology.kubernetes.io/zone"
          operator: "In"
          values: ["ap-northeast-2a", "ap-northeast-2c"]
      limits:
        cpu: "100"
        memory: "400Gi"
      disruption:
        consolidationPolicy: "WhenUnderutilized"
        expireAfter: "30m"
      minReplicas: 2
      maxReplicas: 25