# Istio ConfigMap Configuration for CloudJet
# Configures Zipkin tracing with Jaeger
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istiod
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/part-of: istio
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    release: istiod
data:
  mesh: |
    defaultConfig:
      discoveryAddress: istiod.istio-system.svc:15012
      tracing:
        zipkin:
          address: jaeger-all-in-one.monitoring.svc.cluster.local:9411
    defaultProviders:
      metrics:
      - prometheus
      tracing:
      - jaeger
    extensionProviders:
    - name: jaeger
      zipkin:
        service: jaeger-all-in-one.monitoring.svc.cluster.local
        port: 9411
    enablePrometheusMerge: true
    rootNamespace: istio-system
    trustDomain: cluster.local
  meshNetworks: 'networks: {}'