apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-mesh
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: istio
  namespaceSelector:
    matchNames:
    - user
    - admin
  podMetricsEndpoints:
  - path: /stats/prometheus
    targetPort: 15020
    interval: 15s