# Istio IngressGateway metrics collection
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ingress
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames: [istio-system]
  selector:
    matchLabels:
      istio: ingressgateway
  endpoints:
  - targetPort: 15090
    path: /stats/prometheus
    interval: 15s