{{- if and .Values.k6.enabled .Values.k6.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k6-metrics
  namespace: {{ .Values.k6.serviceMonitor.namespace }}
  labels:
    app: k6-load-test
spec:
  selector:
    matchLabels:
      app: k6-load-test
  endpoints:
  - port: prometheus
    interval: {{ .Values.k6.serviceMonitor.interval }}
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ .Values.global.namespace }}
{{- end }}