# CloudJet Helm Chart Values
# This is a YAML-formatted file for the CloudJet microservices application

# Global settings
global:
  namespace: user  # Default namespace
  applicationNamespaces: ["user", "admin"]
  imagePullPolicy: Always

# Individual microservice configurations
services:
  auth:
    enabled: true
    name: auth-service
    image:
      repository: public.ecr.aws/v3g6g4v7/cj-auth-svc
      tag: v1.0.29
    port: 5001
    replicas: 2
    rollout:
      enabled: true
      autoPromotion: true
      autoPromotionSeconds: 5
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  flight:
    enabled: true
    name: flight-service
    image:
      repository: public.ecr.aws/v3g6g4v7/cj-flight-svc
      tag: v1.0.0
    port: 5002
    replicas: 2
    rollout:
      enabled: true
      autoPromotion: true
      autoPromotionSeconds: 5
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  booking:
    enabled: true
    name: booking-service
    image:
      repository: public.ecr.aws/v3g6g4v7/cj-booking-svc
      tag: v1.0.30
    port: 5003
    replicas: 2
    rollout:
      enabled: true
      autoPromotion: true
      autoPromotionSeconds: 5
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  payment:
    enabled: true
    name: payment-service
    image:
      repository: public.ecr.aws/v3g6g4v7/cj-payment-svc
      tag: v1.0.30
    port: 5005
    replicas: 2
    rollout:
      enabled: true
      autoPromotion: true
      autoPromotionSeconds: 5
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  admin:
    enabled: true
    name: admin-service
    image:
      repository: public.ecr.aws/v3g6g4v7/cj-admin-svc
      tag: v2.0.3
    port: 5004
    namespace: admin  # Admin service goes to admin namespace
    replicas: 1
    rollout:
      enabled: true
      autoPromotion: true
      autoPromotionSeconds: 5
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

# Configuration settings
config:
  # Flask environment
  flaskEnv: production
  pythonPath: /app
  
  # Database settings (non-sensitive)
  database:
    host: db.cloudjet.internal
    name: cloudjet_simple
    user: admin
    port: 3306
    poolSize: 5
  
  # Redis/ElastiCache settings
  redis:
    host: redis.cloudjet.internal
    port: 6379
    db: 0
    ssl: true
  
  # Service URLs for inter-service communication
  serviceUrls:
    auth: http://auth-service-active:5001
    flight: http://flight-service-active:5002
    booking: http://booking-service-active:5003
    payment: http://payment-service-active:5005
    admin: http://admin-service.admin.svc.cluster.local:80
  
  # Cache settings
  cache:
    ttl: 300
    searchTtl: 600

# Secret settings (will be handled by External Secrets)
secrets:
  enabled: true
  externalSecrets:
    enabled: true
    storeName: aws-secrets-store
    serviceAccountName: cloudjet-secrets-sa
 
# ServiceAccounts 설정
serviceAccounts:
  enabled: true
  accounts:
    - name: cloudjet-secrets-sa
      enabled: true
      roleArn: arn:aws:iam::556683426101:role/CloudJetSecretsRole
      namespaces: ["user", "admin"]


# Istio settings
istio:
  enabled: true
  gateway:
    enabled: true
    name: cloudjet-gateway
    hosts:
      - "api.cloudjet.click"
      - "cloudjet.click"
      - "www.cloudjet.click"
      - "kiali.cloudjet.click"
      - "jaeger.cloudjet.click"
      - "grafana.cloudjet.click"
  virtualService:
    enabled: true
    name: cloudjet-vs
    apiHost: "api.cloudjet.click"
    frontendHost: "cloudjet.click"
  destinationRule:
    enabled: true
    name: auth-service-dr
  sidecarInjection:
    enabled: true


# Namespace creation
namespaces:
  - name: user
    istioInjection: enabled
  - name: admin
    istioInjection: enabled
  - name: monitoring