{{- if .Values.karpenter.enabled }}
{{- range $name, $nodeClass := .Values.karpenter.nodeClasses }}
{{- if $nodeClass.name }}
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: {{ $nodeClass.name }}
spec:
  instanceStorePolicy: {{ $nodeClass.instanceStorePolicy | default "RAID0" }}
  amiFamily: {{ $nodeClass.amiFamily | default "AL2023" }}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ $.Values.global.clusterName }}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ $.Values.global.clusterName }}
  role: {{ $nodeClass.role }}
  {{- if $nodeClass.metadataOptions }}
  metadataOptions:
    httpEndpoint: {{ $nodeClass.metadataOptions.httpEndpoint | default "enabled" }}
    httpProtocolIPv6: {{ $nodeClass.metadataOptions.httpProtocolIPv6 | default "disabled" }}
    httpPutResponseHopLimit: {{ $nodeClass.metadataOptions.httpPutResponseHopLimit | default 1 }}
    httpTokens: {{ $nodeClass.metadataOptions.httpTokens | default "required" }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}