global:
  namespace: "user"  # 기존 values.yaml과 일치

keda:
  enabled: true
  prometheus:
    serverAddress: "http://prometheus-prometheus.monitoring.svc.cluster.local:9090"

  scaledObjects:
    # Auth Service - 로그인 버스트 대응
    auth-service:
      enabled: true
      name: "auth-service"
      namespace: "user"
      targetDeployment: "auth-service"
      minReplicas: 2
      maxReplicas: 50
      pollingInterval: 15
      cooldownPeriod: 180
      triggers:
        - type: "cpu"
          metricType: "Utilization"
          value: "70"
        - type: "memory"
          metricType: "Utilization"
          value: "80"

    # Flight Service - 검색 트래픽 변동 대응  
    flight-service:
      enabled: true
      name: "flight-service"
      namespace: "user"
      targetDeployment: "flight-service"
      minReplicas: 2
      maxReplicas: 50
      pollingInterval: 20
      cooldownPeriod: 240
      triggers:
        - type: "cpu"
          metricType: "Utilization"
          value: "70"
        - type: "memory"
          metricType: "Utilization"
          value: "80"

    # Booking Service - 예약 처리 시간 중요
    booking-service:
      enabled: true
      name: "booking-service"
      namespace: "user"
      targetDeployment: "booking-service"
      minReplicas: 2
      maxReplicas: 50
      pollingInterval: 20
      cooldownPeriod: 300
      triggers:
        - type: "cpu"
          metricType: "Utilization"
          value: "70"
        - type: "memory"
          metricType: "Utilization"
          value: "80"

    # Payment Service - 결제 안정성 중요 (에러율 우선)
    payment-service:
      enabled: true
      name: "payment-service"
      namespace: "user"
      targetDeployment: "payment-service"
      minReplicas: 1
      maxReplicas: 50
      pollingInterval: 15
      cooldownPeriod: 300
      triggers:
        - type: "cpu"
          metricType: "Utilization"
          value: "70"
        - type: "memory"
          metricType: "Utilization"
          value: "80"

    # Admin Service - 관리 기능 (안정적 운영)
    admin-service:
      enabled: true
      name: "admin-service"
      namespace: "admin"
      targetDeployment: "admin-service"
      minReplicas: 1
      maxReplicas: 4
      pollingInterval: 60
      cooldownPeriod: 600
      triggers:
        - type: "prometheus"
          metricName: "admin_service_rps"
          query: 'rate(istio_requests_total{destination_service_name="admin-service"}[1m])'
          threshold: "5"

